version: '3.9'

services:
  client:
    image: cloudcarbonfootprint/client:latest
    ports:
      - '80:80'
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
  api:
    image: cloudcarbonfootprint/api:latest
    env_file: 
      - ./packages/api/.env  # Relative path to env file (from compose file location)
    ports:
      - '8080:8080'
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials  # Mount AWS credentials
      - ./packages/api:/app  # Mount project directory
    environment:
      - NODE_ENV=production
